apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "finance-portal-backend-service.fullname" . }}
  labels:
    app: {{ template "finance-portal-backend-service.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  SETTLEMENTS_ENDPOINT: {{ (printf "http://%s-%s" .Release.Name .Values.config.settlementsEndpoint) | quote }}
  CENTRAL_LEDGER_ENDPOINT: {{ (printf "http://%s-%s" .Release.Name .Values.config.centralLedgerEndpoint) | quote }}
  HUB_REPORT_URL_312: {{ (printf "http://%s-%s" .Release.Name .Values.config.report312) | quote }}
  HUB_REPORT_URL_644: {{ (printf "http://%s-%s" .Release.Name .Values.config.report644) | quote }}
  SETTLEMENT_MANAGEMENT_ENDPOINT: {{ (printf "%s%s-%s:%s" "http://" .Release.Name .Values.config.settlementManagementEndpoint .Values.config.settlementManagementPort) | quote }}
  LISTEN_PORT: "3000"
  NODE_ENV: "production"
  BYPASS_AUTH:  {{ .Values.config.wso2BypassAuth | quote }}
  INSECURE_COOKIE: {{ .Values.config.wso2InsecureCookie | quote }}
  AUTH_SERVER: {{ .Values.config.wso2oauthServer | quote }}
  AUTH_SERVER_PORT: {{ .Values.config.wso2oauthPort | quote }}
  AUTH_SERVICE: {{ .Values.config.wso2oauthLoginPath | quote }}
  VALIDATE_SERVICE: {{ .Values.config.wso2oauthTokenValidationPath | quote }}
  USERINFO_SERVICE: {{ .Values.config.wso2oauthUserInfo | quote }}
  REVOKE_SERVICE: {{ .Values.config.wso2oauthTokenRevoke | quote }}
