apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "finance-portal-backend-service.fullname" . }}
  labels:
    app: {{ template "finance-portal-backend-service.name" . }}
    chart: {{ template "finance-portal-backend-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "finance-portal-backend-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "finance-portal-backend-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init
          image: {{ .Values.init.image }}
          imagePullPolicy: {{ .Values.init.pullPolicy }}
          envFrom:
            - configMapRef:
                name: wso2is-populate
            - secretRef:
                name: {{ template "finance-portal-backend-service.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        envFrom:
          - configMapRef:
              name: {{ template "finance-portal-backend-service.fullname" . }}
          - secretRef:
              name: {{ template "finance-portal-backend-service.fullname" . }}
        volumeMounts:
          - name: {{ template "finance-portal-backend-service.fullname" . }}-volume
            mountPath: {{ .Values.secretsMountPoint }}
        resources:
      volumes:
        - name: {{ template "finance-portal-backend-service.fullname" . }}-volume

      imagePullSecrets:
      - name: {{ .Values.imageCredentials.name }}
